# Generated by Django 4.1.5 on 2023-01-18 03:18

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=300)),
                ('channel', models.CharField(choices=[('FB_COM', 'Facebook Community'), ('FB_PER', 'Facebook Personal'), ('TIK_COM', 'Tiktok Community'), ('TIK_PER', 'Tiktok Personal'), ('YOU_COM', 'Youtube Community'), ('YOU_PER', 'Youtube Personal'), ('INST', 'Instagram'), ('FORUM', 'Forum'), ('WEBSITE', 'Website'), ('LINKEDIN', 'Linkedin'), ('OTHERS', 'Others')], max_length=8)),
                ('follower', models.CharField(max_length=20)),
                ('engagement_rate_percent', models.CharField(max_length=10)),
                ('location', models.CharField(choices=[('HCM', 'Hồ Chí Minh'), ('HN', 'Hà Nội')], default='HCM', max_length=3)),
                ('year_of_birth', models.CharField(max_length=4)),
                ('gender', models.CharField(choices=[('Ma', 'Male'), ('Fe', 'Female')], default='Ma', max_length=2)),
                ('fields', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Singer'), (2, 'Dancer'), (3, 'Actor/Actress'), (4, 'Rapper'), (5, 'DJ')], max_length=3)),
                ('original_cost_picture', models.CharField(max_length=50, null=True)),
                ('original_cost_video', models.CharField(max_length=50, null=True)),
                ('original_cost_event', models.CharField(max_length=50, null=True)),
                ('kpi', models.CharField(max_length=50, null=True)),
                ('discount', models.CharField(max_length=50, null=True)),
                ('supplier_name', models.CharField(max_length=100, null=True)),
                ('booking_contact_name', models.CharField(max_length=100, null=True)),
                ('booking_contact_phone', models.CharField(max_length=15, null=True)),
                ('booking_contact_email', models.CharField(max_length=50, null=True)),
                ('latest_update', models.DateTimeField(auto_now_add=True)),
                ('handle_by', models.CharField(max_length=100)),
                ('group_chat_name', models.CharField(max_length=100)),
                ('kenh', models.CharField(choices=[('za', 'Zalo'), ('vi', 'Viber'), ('fb', 'Facebook')], default='za', max_length=2)),
                ('lana_leader', models.BooleanField(default=False)),
                ('history', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
