# Generated by Django 4.1.5 on 2023-01-18 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierModel',
            new_name='Supplier',
        ),
    ]
