# Generated by Django 4.1.5 on 2023-01-18 03:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_rename_suppliermodel_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='engagement_rate_percent',
            new_name='Engagement Rate (%)',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Singer'), (2, 'Dancer'), (3, 'Actor/Actress'), (4, 'Rapper'), (5, 'DJ'), (6, 'Music Producer'), (7, 'Director'), (8, 'Entertaiment'), (9, 'Content Creator'), (10, 'Gymer/Fitness'), (11, 'Teacher/ Coach'), (12, 'Model'), (13, 'Interior house'), (14, 'Footballer')], max_length=3),
        ),
    ]
