# Generated by Django 4.1.5 on 2023-01-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0004_alter_supplier_booking_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='Engagement Rate (%)',
            new_name='Engagement Rate (Percent)',
        ),
    ]
