# Generated by Django 4.1.5 on 2023-01-18 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0007_alter_supplier_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='Engagement Rate (Percent)',
            new_name='engagement_rate_percent',
        ),
    ]
