# Generated by Django 4.1.5 on 2023-01-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0008_rename_engagement rate (percent)_supplier_engagement_rate_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
    ]
