# Generated by Django 4.1.5 on 2023-01-18 09:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0009_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='channel',
            field=models.CharField(choices=[('Facebook Community', 'Facebook Community'), ('Facebook Personal', 'Facebook Personal'), ('Tiktok Community', 'Tiktok Community'), ('Tiktok Personal', 'Tiktok Personal'), ('Youtube Community', 'Youtube Community'), ('Youtube Personal', 'Youtube Personal'), ('Instagram', 'Instagram'), ('Forum', 'Forum'), ('Website', 'Website'), ('Linkedin', 'Linkedin'), ('Others', 'Others')], max_length=18),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Singer', 'Singer'), ('Dancer', 'Dancer'), ('Actor/Actress', 'Actor/Actress'), ('Rapper', 'Rapper'), ('DJ', 'DJ'), ('Music Producer', 'Music Producer'), ('Director', 'Director'), ('Entertaiment', 'Entertaiment'), ('Content Creator', 'Content Creator'), ('Gymer/Fitness', 'Gymer/Fitness'), ('Teacher/ Coach', 'Teacher/ Coach'), ('Model', 'Model'), ('Interior house', 'Interior house'), ('Footballer', 'Footballer')], max_length=500),
        ),
    ]
