# Generated by Django 4.1.5 on 2023-01-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0012_alter_supplier_latest_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='latest_update',
            field=models.DateTimeField(),
        ),
    ]
