# Generated by Django 4.1.5 on 2023-01-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0014_alter_supplier_fields_alter_supplier_kpi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='engagement_rate_percent',
            field=models.CharField(max_length=10, verbose_name='ER(%)'),
        ),
    ]
