# Generated by Django 4.1.5 on 2023-01-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0015_alter_supplier_engagement_rate_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='kenh',
        ),
        migrations.AddField(
            model_name='supplier',
            name='group_chat_channel',
            field=models.CharField(choices=[('za', 'Zalo'), ('vi', 'Viber'), ('fb', 'Facebook')], default='za', max_length=2, verbose_name='Group Chat Channel'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='original_cost_tvc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ORIGINAL COST - TVC'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='profile_quotation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PROFILE/QUOTATION'),
        ),
    ]
