# Generated by Django 4.1.5 on 2023-01-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0016_remove_supplier_kenh_supplier_group_chat_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='follower_2',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
