# Generated by Django 4.1.5 on 2023-01-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0017_supplier_follower_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='follower_2',
        ),
    ]
