# Generated by Django 4.1.5 on 2023-01-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0018_remove_supplier_follower_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='discount',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='engagement_rate_percent',
            field=models.FloatField(max_length=10, verbose_name='ER(%)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='kpi',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='KPI'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='year_of_birth',
            field=models.IntegerField(max_length=4),
        ),
    ]
