# Generated by Django 4.1.5 on 2023-01-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0020_alter_supplier_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_event',
            field=models.FloatField(blank=True, null=True, verbose_name='ORIGINAL COST - EVENT'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_picture',
            field=models.FloatField(blank=True, null=True, verbose_name='ORIGINAL COST - PICTURE'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_tvc',
            field=models.FloatField(blank=True, null=True, verbose_name='ORIGINAL COST - TVC'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_video',
            field=models.FloatField(blank=True, null=True, verbose_name='ORIGINAL COST - VIDEO'),
        ),
    ]
