# Generated by Django 4.1.5 on 2023-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0021_alter_supplier_original_cost_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='follower_2',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
