# Generated by Django 4.1.5 on 2023-01-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0022_supplier_follower_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='kol_tier',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='follower_2',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
