# Generated by Django 4.1.5 on 2023-01-31 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0024_supplier_engagement_rate_absolute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='year_of_birth',
            field=models.IntegerField(blank=True, default=1900, validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
