# Generated by Django 4.1.5 on 2023-02-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0025_alter_supplier_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='engagement_rate_absolute',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='ER (Ab.)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='engagement_rate_percent',
            field=models.FloatField(null=True, verbose_name='ER(%)'),
        ),
    ]
