# Generated by Django 4.1.5 on 2023-02-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0030_alter_supplier_original_cost_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='follower_2',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='kpi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='KPI'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_event',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='ORIGINAL COST - EVENT'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_tvc',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='ORIGINAL COST - TVC'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_video',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='ORIGINAL COST - VIDEO'),
        ),
    ]
