# Generated by Django 4.1.5 on 2023-02-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0032_alter_supplier_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile', verbose_name='PROFILE/QUOTATION'),
        ),
    ]
