# Generated by Django 4.1.5 on 2023-02-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0033_supplier_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='profile_quotation',
        ),
    ]
