# Generated by Django 4.1.5 on 2023-02-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0034_remove_supplier_profile_quotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': [('export_excel_as_staff', 'Can export excel with limit 100 records'), ('export_excel_as_admin', 'Can export excel with limit 1000 records')]},
        ),
    ]
