# Generated by Django 4.1.5 on 2023-02-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0036_alter_supplier_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='engagement_rate_absolute_display',
        ),
    ]
