# Generated by Django 4.1.5 on 2023-02-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0037_remove_supplier_engagement_rate_absolute_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': [('import_data_as_admin', 'Can import data'), ('export_excel_as_staff', 'Can export excel with limit 100 records'), ('export_excel_as_admin', 'Can export excel with limit 1000 records')]},
        ),
    ]
