# Generated by Django 4.1.5 on 2023-02-03 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0038_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='booking_contact_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='booking_contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='booking_contact_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='discount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='engagement_rate_absolute',
            field=models.FloatField(editable=False, null=True, verbose_name='ER (Ab.)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='follower_2',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='group_chat_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='handle_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='kol_tier',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='kpi',
            field=models.CharField(max_length=50, null=True, verbose_name='KPI'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_event',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='ORIGINAL COST - EVENT'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_picture',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='ORIGINAL COST - PICTURE'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_tvc',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='ORIGINAL COST - TVC'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_video',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='ORIGINAL COST - VIDEO'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='profile',
            field=models.CharField(max_length=300, null=True, verbose_name='PROFILE/QUOTATION'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='year_of_birth',
            field=models.IntegerField(default=1900, validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
