# Generated by Django 4.1.5 on 2023-02-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0041_alter_supplier_lana_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='location',
            field=models.CharField(choices=[('An Giang', 'An Giang'), ('Bà Rịa-Vũng Tàu', 'Bà Rịa-Vũng Tàu'), ('Bạc Liêu', 'Bạc Liêu'), ('Bắc Kạn', 'Bắc Kạn'), ('Bắc Giang', 'Bắc Giang'), ('Bắc Ninh', 'Bắc Ninh'), ('Bến Tre', 'Bến Tre'), ('Bình Dương', 'Bình Dương'), ('Bình Định', 'Bình Định'), ('Bình Phước', 'Bình Phước'), ('Bình Thuận', 'Bình Thuận'), ('Cà Mau', 'Cà Mau'), ('Cao Bằng', 'Cao Bằng'), ('Cần Thơ', 'Cần Thơ'), ('Đà Nẵng', 'Đà Nẵng'), ('Đắk Lắk', 'Đắk Lắk'), ('Đắk Nông', 'Đắk Nông'), ('Điện Biên', 'Điện Biên'), ('Đồng Nai', 'Đồng Nai'), ('Đồng Tháp', 'Đồng Tháp'), ('GL', 'Gia Lai'), ('HG', 'Hà Giang'), ('HNA', 'Hà Nam'), ('HN', 'Hà Nội'), ('HT', 'Hà Tĩnh'), ('HD', 'Hải Dương'), ('HP', 'Hải Phòng'), ('HGI', 'Hậu Giang'), ('HB', 'Hòa Bình'), ('SG', 'Thành phố Hồ Chí Minh'), ('HY', 'Hưng Yên'), ('KH', 'Khánh Hoà'), ('KG', 'Kiên Giang'), ('KT', 'Kon Tum'), ('LC', 'Lai Châu'), ('LS', 'Lạng Sơn'), ('LCA', 'Lào Cai'), ('LĐ', 'Lâm Đồng'), ('LA', 'Long An'), ('NĐ', 'Nam Định'), ('NA', 'Nghệ An'), ('NB', 'Ninh Bình'), ('NT', 'Ninh Thuận'), ('PT', 'Phú Thọ'), ('PY', 'Phú Yên'), ('QB', 'Quảng Bình'), ('QNA', 'Quảng Nam'), ('QNG', 'Quảng Ngãi'), ('QN', 'Quảng Ninh'), ('QT', 'Quảng Trị'), ('ST', 'Sóc Trăng'), ('SL', 'Sơn La'), ('TN', 'Tây Ninh'), ('TB', 'Thái Bình'), ('TNG', 'Thái Nguyên'), ('TH', 'Thanh Hóa'), ('TTH', 'Thừa Thiên-Huế'), ('TG', 'Tiền Giang'), ('TV', 'Trà Vinh'), ('TQ', 'Tuyên Quang'), ('VL', 'Vĩnh Long'), ('VP', 'Vĩnh Phúc'), ('YB', 'Yên Bái')], default='SG', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_event',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='Org. cost - Event'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_picture',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='Org. cost - Picture'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_tvc',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='Org. cost - TVC'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='original_cost_video',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='Org. cost - Video'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='profile',
            field=models.CharField(max_length=300, null=True, verbose_name='Profile/Quatation'),
        ),
    ]
