# Generated by Django 4.1.5 on 2023-02-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0043_alter_supplier_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='group_chat_channel',
            field=models.CharField(choices=[('Zalo', 'Zalo'), ('Viber', 'Viber'), ('Facebook', 'Facebook')], default='Zalo', max_length=8, verbose_name='Group Chat Channel'),
        ),
    ]
