# Generated by Django 4.1.5 on 2023-02-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0044_alter_supplier_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='channel',
            field=models.CharField(choices=[('Facebook Group', 'Facebook Group'), ('Facebook Fanpage', 'Facebook Fanpage'), ('Facebook Personal', 'Facebook Personal'), ('Tiktok Community', 'Tiktok Community'), ('Tiktok Personal', 'Tiktok Personal'), ('Youtube Community', 'Youtube Community'), ('Youtube Personal', 'Youtube Personal'), ('Instagram', 'Instagram'), ('Forum', 'Forum'), ('Website', 'Website'), ('Linkedin', 'Linkedin'), ('Others', 'Others')], max_length=18),
        ),
    ]
