# Generated by Django 4.1.5 on 2023-02-06 07:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0046_alter_supplier_group_chat_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='channel',
            field=models.CharField(choices=[('Facebook Group', 'Facebook Group'), ('Facebook Fanpage', 'Facebook Fanpage'), ('Facebook Personal', 'Facebook Personal'), ('Tiktok Community', 'Tiktok Community'), ('Tiktok Personal', 'Tiktok Personal'), ('Youtube Community', 'Youtube Community'), ('Youtube Personal', 'Youtube Personal'), ('Instagram', 'Instagram'), ('Forum', 'Forum'), ('Website', 'Website'), ('Linkedin', 'Linkedin'), ('Others', 'Others')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Singer', 'Singer'), ('Rapper', 'Rapper'), ('DJ', 'DJ'), ('Music Producer', 'Music Producer'), ('Dancer', 'Dancer'), ('Streamer', 'Streamer'), ('Content Creator', 'Content Creator'), ('Reviewer', 'Reviewer'), ('Blogger', 'Blogger'), ('Footballer', 'Footballer'), ('Gymer/Fitness', 'Gymer/Fitness'), ('Model', 'Model'), ('Showbiz', 'Showbiz'), ('Make-up', 'Make-up'), ('Cosmestic/Skincare', 'Cosmestic/Skincare'), ('Fashion', 'Fashion'), ('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('News', 'News'), ('Education', 'Education'), ('Teacher/Coach', 'Teacher/Coach'), ('Office staff', 'Office staff'), ('Freelancer', 'Freelancer'), ('Business', 'Business'), ('Lawyer', 'Lawyer'), ('Student', 'Student'), ('Doctor', 'Doctor'), ('Architect', 'Architect'), ('Smarthome', 'Smarthome'), ('Home appliance', 'Home appliance'), ('Interior house', 'Interior house'), ('Decor & Design', 'Decor & Design'), ('Investment', 'Investment'), ('Insurance', 'Insurance'), ('Economics & Law', 'Economics & Law'), ('Capital Market ', 'Capital Market '), ('Banking', 'Banking'), ('Kid', 'Kid'), ('Hot Mom/Dad', 'Hot Mom/Dad'), ('Automotive', 'Automotive'), ('Director', 'Director'), ('Actor/Actress', 'Actor/Actress'), ('Health & Medicine', 'Health & Medicine'), ('Youth & GenZ', 'Youth & GenZ'), ('Media & Advertisement', 'Media & Advertisement'), ('Game & Esport', 'Game & Esport'), ('MC & Editor', 'MC & Editor'), ('Food & Drink', 'Food & Drink'), ('Technology & Ecommerce', 'Technology & Ecommerce'), ('Celeb', 'Celeb'), ('General', 'General'), ('Other', 'Other')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='group_chat_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='handle_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='history',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='latest_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='location',
            field=models.CharField(choices=[('An Giang', 'An Giang'), ('Bà Rịa-Vũng Tàu', 'Bà Rịa-Vũng Tàu'), ('Bạc Liêu', 'Bạc Liêu'), ('Bắc Kạn', 'Bắc Kạn'), ('Bắc Giang', 'Bắc Giang'), ('Bắc Ninh', 'Bắc Ninh'), ('Bến Tre', 'Bến Tre'), ('Bình Dương', 'Bình Dương'), ('Bình Định', 'Bình Định'), ('Bình Phước', 'Bình Phước'), ('Bình Thuận', 'Bình Thuận'), ('Cà Mau', 'Cà Mau'), ('Cao Bằng', 'Cao Bằng'), ('Cần Thơ', 'Cần Thơ'), ('Đà Nẵng', 'Đà Nẵng'), ('Đắk Lắk', 'Đắk Lắk'), ('Đắk Nông', 'Đắk Nông'), ('Điện Biên', 'Điện Biên'), ('Đồng Nai', 'Đồng Nai'), ('Đồng Tháp', 'Đồng Tháp'), ('Gia Lai', 'Gia Lai'), ('Hà Giang', 'Hà Giang'), ('Hà Nam', 'Hà Nam'), ('Hà Nội', 'Hà Nội'), ('Hà Tĩnh', 'Hà Tĩnh'), ('Hải Dương', 'Hải Dương'), ('Hải Phòng', 'Hải Phòng'), ('Hậu Giang', 'Hậu Giang'), ('Hòa Bình', 'Hòa Bình'), ('Hồ Chí Minh', 'Thành phố Hồ Chí Minh'), ('Hưng Yên', 'Hưng Yên'), ('Khánh Hoà', 'Khánh Hoà'), ('Kiên Giang', 'Kiên Giang'), ('Kon Tum', 'Kon Tum'), ('Lai Châu', 'Lai Châu'), ('Lạng Sơn', 'Lạng Sơn'), ('Lào Cai', 'Lào Cai'), ('Lâm Đồng', 'Lâm Đồng'), ('Long An', 'Long An'), ('Nam Định', 'Nam Định'), ('Nghệ An', 'Nghệ An'), ('Ninh Bình', 'Ninh Bình'), ('Ninh Thuận', 'Ninh Thuận'), ('Phú Thọ', 'Phú Thọ'), ('Phú Yên', 'Phú Yên'), ('Quảng Bình', 'Quảng Bình'), ('Quảng Nam', 'Quảng Nam'), ('Quảng Ngãi', 'Quảng Ngãi'), ('Quảng Ninh', 'Quảng Ninh'), ('Quảng Trị', 'Quảng Trị'), ('Sóc Trăng', 'Sóc Trăng'), ('Sơn La', 'Sơn La'), ('Tây Ninh', 'Tây Ninh'), ('Thái Bình', 'Thái Bình'), ('Thái Nguyên', 'Thái Nguyên'), ('Thanh Hóa', 'Thanh Hóa'), ('Thừa Thiên-Huế', 'Thừa Thiên-Huế'), ('Tiền Giang', 'Tiền Giang'), ('Trà Vinh', 'Trà Vinh'), ('Tuyên Quang', 'Tuyên Quang'), ('Vĩnh Long', 'Vĩnh Long'), ('Vĩnh Phúc', 'Vĩnh Phúc'), ('Yên Bái', 'Yên Bái')], default='Hồ Chí Minh', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
