# Generated by Django 4.1.5 on 2023-02-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0047_alter_supplier_channel_alter_supplier_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='group_chat_channel',
            field=models.CharField(choices=[('Zalo', 'Zalo'), ('Viber', 'Viber'), ('Facebook', 'Facebook')], max_length=8, null=True, verbose_name='Group Chat Channel'),
        ),
    ]
