# Generated by Django 4.1.5 on 2023-02-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0049_alter_supplier_gender_alter_supplier_lana_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='lana_leader',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
