# Generated by Django 4.1.5 on 2023-02-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0050_alter_supplier_lana_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': [('import_data_as_admin', 'Can import data'), ('export_excel_50', 'Can export excel with limit 50 records'), ('export_excel_100', 'Can export excel with limit 100 records'), ('export_excel_1000', 'Can export excel with limit 1000 records')]},
        ),
    ]
