# Generated by Django 4.1.5 on 2023-02-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0052_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': [('import_data_as_admin', 'Can import data'), ('export_excel_50', 'Can export excel as a seller role (50)'), ('export_excel_100', 'Can export excel as a buyer role (100)'), ('export_excel_1000', 'Can export excel as a admin')]},
        ),
    ]
