# Generated by Django 4.1.5 on 2023-02-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0058_alter_supplier_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(editable=False, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
