# Generated by Django 4.1.5 on 2023-02-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0059_backgroundlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundlog',
            name='isError',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
