# Generated by Django 4.1.5 on 2023-02-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0060_backgroundlog_iserror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundlog',
            name='isError',
        ),
        migrations.AddField(
            model_name='backgroundlog',
            name='isSuccess',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
