# Generated by Django 4.1.5 on 2023-02-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0061_remove_backgroundlog_iserror_backgroundlog_issuccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundlog',
            name='log',
            field=models.TextField(null=True),
        ),
    ]
