# Generated by Django 4.1.5 on 2023-02-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0063_delete_backgroundlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': [('import_data_as_admin', 'Can import data'), ('export_excel_50_seller', 'Can export excel as a seller role (50)'), ('export_excel_100_buyer', 'Can export excel as a buyer role (100)'), ('export_excel_1000_admin', 'Can export excel as an admin role')]},
        ),
    ]
