# Generated by Django 4.1.5 on 2023-02-17 04:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0064_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Singer', 'Singer'), ('Rapper', 'Rapper'), ('DJ', 'DJ'), ('Music Producer', 'Music Producer'), ('Dancer', 'Dancer'), ('Streamer', 'Streamer'), ('Content Creator', 'Content Creator'), ('Reviewer', 'Reviewer'), ('Blogger', 'Blogger'), ('Footballer', 'Footballer'), ('Gymer/Fitness', 'Gymer/Fitness'), ('Model', 'Model'), ('Showbiz', 'Showbiz'), ('Make-up', 'Make-up'), ('Cosmetic/Skincare', 'Cosmetic/Skincare'), ('Fashion', 'Fashion'), ('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('News', 'News'), ('Education', 'Education'), ('Teacher/Coach', 'Teacher/Coach'), ('Office staff', 'Office staff'), ('Freelancer', 'Freelancer'), ('Business', 'Business'), ('Lawyer', 'Lawyer'), ('Student', 'Student'), ('Doctor', 'Doctor'), ('Architect', 'Architect'), ('Smarthome', 'Smarthome'), ('Home appliance', 'Home appliance'), ('Interior house', 'Interior house'), ('Decor & Design', 'Decor & Design'), ('Investment', 'Investment'), ('Insurance', 'Insurance'), ('Economics & Law', 'Economics & Law'), ('Capital Market', 'Capital Market'), ('Banking', 'Banking'), ('Kid', 'Kid'), ('Hot Mom/Dad', 'Hot Mom/Dad'), ('Automotive', 'Automotive'), ('Director', 'Director'), ('Actor/Actress', 'Actor/Actress'), ('Health & Medicine', 'Health & Medicine'), ('Youth & GenZ', 'Youth & GenZ'), ('Media & Advertisement', 'Media & Advertisement'), ('Game & Esport', 'Game & Esport'), ('MC & Editor', 'MC & Editor'), ('Food & Drink', 'Food & Drink'), ('Technology & Ecommerce', 'Technology & Ecommerce'), ('Celeb', 'Celeb'), ('General', 'General'), ('Other', 'Other')], max_length=500, null=True),
        ),
    ]
