# Generated by Django 4.1.5 on 2023-02-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0066_alter_supplier_fields_alter_supplier_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('General', 'General')], max_length=10, null=True),
        ),
    ]
