# Generated by Django 4.1.5 on 2023-03-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0071_alter_supplier_booking_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='kpi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='KPI'),
        ),
    ]
