# Generated by Django 4.1.5 on 2023-03-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0073_alter_supplier_booking_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='booking_contact_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='booking_contact_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='booking_contact_phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='discount',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='kpi',
            field=models.CharField(max_length=150, null=True, verbose_name='KPI'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
