# Generated by Django 4.1.5 on 2023-02-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_syncconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncconfig',
            old_name='isEnable',
            new_name='is_enable',
        ),
    ]
