# Generated by Django 4.1.5 on 2023-02-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_rename_isenable_syncconfig_is_enable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncconfig',
            old_name='is_enable',
            new_name='fri',
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='mon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='sat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='sun',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='thu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='tue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='wed',
            field=models.BooleanField(default=True),
        ),
    ]
