# Generated by Django 4.1.7 on 2023-03-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_rename_is_enable_syncconfig_fri_syncconfig_mon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundLogDevOnly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('isSuccess', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
